[package]
name = "perf_course"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
mach = "0.3.2"
libc = "0.2.154"
memmap2 = "0.9.4"
rand = "0.8.4"
once_cell = "1.19.0"

[profile.dev]
opt-level = 1
